# fly.toml app configuration file generated for megaverse-store-delicate-forest-1385 on 2024-05-15T21:32:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'megaverse-store'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
